version: 2

models:
  - name: dim_commodity
    description: "Unique list of commodities and unit amounts."

    columns:
      - name: commodity_id
        description: "Surrogate key for a commodity and unit combinations."
        tests:
          - not_null
          - unique

      - name: commodity_name
        description: "Normalized commodity name."
        tests:
          - not_null

      - name: unit_amount
        description: "Unit and quantity."
        tests:
          - not_null

  - name: fct_commodity_prices
    description: "Commodity prices over time."

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - commodity_id
              - date_id

    columns:
      - name: commodity_id
        tests:
          - not_null

      - name: date_id
        tests:
          - not_null

      - name: price
        tests:
          - not_null
