version: 2

models:
  - name: dim_commodities
    description: "Unique list of commodities and unit amounts."

    columns:
      - name: commodity_id
        description: "Surrogate key for a commodity and unit combinations."
        tests:
          - not_null
          - unique

      - name: commodity_name
        description: "Normalized commodity name."
        tests:
          - not_null

      - name: unit_amount
        description: "Unit and quantity."
        tests:
          - not_null

  - name: fct_commodity_prices_gaza
    description: "Commodity prices over time."

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - commodity_name
            - unit_amount
            - price_date

    columns:
      - name: commodity_name
        tests:
          - not_null

      - name: unit_amount
        tests:
          - not_null

      - name: price_date
        tests:
          - not_null

      - name: price
        tests:
          - not_null
